
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "EcommerceWS", targetNamespace = "http://presentation.soap.formations.ma/", wsdlLocation = "http://localhost:9999/ecommerce?wsdl")
public class EcommerceWS
    extends Service
{

    private static final URL ECOMMERCEWS_WSDL_LOCATION;
    private static final WebServiceException ECOMMERCEWS_EXCEPTION;
    private static final QName ECOMMERCEWS_QNAME = new QName("http://presentation.soap.formations.ma/", "EcommerceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ecommerce?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ECOMMERCEWS_WSDL_LOCATION = url;
        ECOMMERCEWS_EXCEPTION = e;
    }

    public EcommerceWS() {
        super(__getWsdlLocation(), ECOMMERCEWS_QNAME);
    }

    public EcommerceWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ECOMMERCEWS_QNAME, features);
    }

    public EcommerceWS(URL wsdlLocation) {
        super(wsdlLocation, ECOMMERCEWS_QNAME);
    }

    public EcommerceWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ECOMMERCEWS_QNAME, features);
    }

    public EcommerceWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EcommerceWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ArticleSoapController
     */
    @WebEndpoint(name = "ArticleSoapControllerPort")
    public ArticleSoapController getArticleSoapControllerPort() {
        return super.getPort(new QName("http://presentation.soap.formations.ma/", "ArticleSoapControllerPort"), ArticleSoapController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArticleSoapController
     */
    @WebEndpoint(name = "ArticleSoapControllerPort")
    public ArticleSoapController getArticleSoapControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://presentation.soap.formations.ma/", "ArticleSoapControllerPort"), ArticleSoapController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ECOMMERCEWS_EXCEPTION!= null) {
            throw ECOMMERCEWS_EXCEPTION;
        }
        return ECOMMERCEWS_WSDL_LOCATION;
    }

}
